# -*- coding: utf-8 -*-
"""Untitled14.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1GHRTzDLUPCDPcif57pxUHrdLwtj5bu1P

# Подгружаю Библиотеки, инструменты
"""

!nvidia-smi

!pip uninstall -y llama-cpp-python
!pip install llama-cpp-python --extra-index-url https://abetlen.github.io/llama-cpp-python/whl/cu124-

from google.colab import drive
drive.mount('/content/drive')

from huggingface_hub import hf_hub_download

model_path = hf_hub_download(
    repo_id="bartowski/Qwen2.5-7B-Instruct-GGUF",
    filename="Qwen2.5-7B-Instruct-Q4_K_M.gguf",
    local_dir="/content/drive/MyDrive/models"
)
print(model_path)

"""# Настройка пайплайна"""

from llama_cpp import Llama

llm = Llama(
    model_path="/content/drive/MyDrive/models/Qwen2.5-7B-Instruct-Q4_K_M.gguf",
    n_ctx=4096,          # размер контекста
    n_gpu_layers=-1,     # -1 = выгрузить все слои на GPU
    n_threads=8,         # количество CPU-потоков
    verbose=True
)

output = llm.create_chat_completion(
    messages=[
        {"role": "system", "content": "Ты - эксперт в области правил дорожного движения. Отвечай на вопросы"},
        {"role": "user", "content": "Привет! Могу ли я пересечь сплошную полосу на автомобиле?"}
    ],
    max_tokens=512,
    temperature=0
)

print(output["choices"][0]["message"]["content"])

#как мы видим модель глупая и совсем не разбирается в пдд.

"""# готовим файлы, нарезаем на чанки"""

!apt-get install -y libreoffice
!libreoffice --headless --convert-to txt pdd.doc

from sentence_transformers import SentenceTransformer
model = SentenceTransformer('BAAI/bge-m3')
#embeddings = model.encode(chunks, normalize_embeddings=True)

import re

with open("/content/pdd.txt", "r", encoding="utf-8") as f:
    text = f.read()

# Ищем начало пункта: номер (2-3 уровня) + точка + пробел, в начале строки
pattern = re.compile(r'(?m)^(\d{1,2}\.\d{1,2}(?:\.\d{1,2})?\.?\d?)\.\s+')

matches = list(pattern.finditer(text))

chunks = []
for i, m in enumerate(matches):
    start = m.start()
    end = matches[i+1].start() if i+1 < len(matches) else len(text)
    point_id = m.group(1)
    chunk_text = text[start:end].strip()
    chunks.append({"point": point_id, "text": chunk_text})
for c in chunks[:20]:
    print(c["point"], "->", c["text"][:100])

#тк чанк с терминами(1.2) огромный ,режу его

import re

terms_chunk = next(c for c in chunks if c["point"] == "1.2")
terms_text = terms_chunk["text"]

first_quote = terms_text.find('"')
terms_text = terms_text[first_quote:]

#regex под термин-определение до следующей ковычки
term_pattern = re.compile(r'"([^"]+)"\s*[-–]\s*(.+?)(?=\n"|\Z)', re.DOTALL)
terms_found = term_pattern.findall(terms_text)

for term,definition in terms_found[:20]:
  print(term,definition)

term_chunks = []
for term, definition in terms_found:
    definition = definition.strip()
    term_chunks.append({
        "point": None,
        "term": term,
        "section_type": "term",
        "text": f'"{term}" - {definition}'
    })

# 4. Удаляем старый склеенный чанк 1.2 и добавляем на его место разобранные термины
chunks = [c for c in chunks if c["point"] != "1.2"]
chunks.extend(term_chunks)

for t in term_chunks[:5]:
    print(t["term"], "->", t["text"][:80])
print("...")
print("Всего терминов:", len(term_chunks))

for c in chunks[:20]:
    print(c["point"], "->", c["text"][:100])

print(chunks[:-70])

for c in chunks:
    print(f"[{c['point']}] {c['text']}")
    print('-' * 80)

def parse_chapters(rule_text):
    chapter_pattern = re.compile(r'(?m)^(\d{1,2})\.\s+([А-ЯЁ][^\n]*)$')
    return [(m.start(), f"{m.group(1)}. {m.group(2).strip()}")
            for m in chapter_pattern.finditer(rule_text)]

def find_chapter(offset, chapters):
    current = None
    for pos, title in chapters:
        if pos <= offset:
            current = title
        else:
            break
    return current
rule_text=text
chapters = parse_chapters(rule_text)   # rule_text — исходный текст секции с правилами

for c in chunks:
    pos = rule_text.find(c["text"][:30])   # ищем позицию чанка в исходном тексте
    c["chapter"] = find_chapter(pos, chapters)

for c in chunks[:270]:
    print(c)

chapter_tail = re.compile(r'\n\d{1,2}\.\s+[А-ЯЁ].*$', re.DOTALL)
for c in chunks:
    m = chapter_tail.search(c["text"])
    if m:
        c["text"] = c["text"][:m.start()].strip()

import re

# ------------------------------------------------------------
# 1. Находим позиции разделов в общем тексте
# ------------------------------------------------------------
pos_app1 = text.find("Приложение 1")
pos_app2 = text.find("Приложение 2")
# Основные положения находятся после приложений (после "Приложение N 3")
pos_base = text.find("Приложение N 3")


print(f"Позиции: Приложение1={pos_app1}, Приложение2={pos_app2}, Основные положения={pos_base}")

# ------------------------------------------------------------
# 2. Отфильтровываем из исходного chunks только основные правила (до Приложения 1)
#    и термины (они уже добавлены отдельно и находятся до pos_app1)
# ------------------------------------------------------------
main_chunks = []
for c in chunks:
    # Ищем позицию первого вхождения текста чанка в общем тексте
    # (берём первые 50 символов для надёжности)
    sample = c['text'][:50]
    pos = text.find(sample)
    if pos != -1 and pos < pos_app1:
        main_chunks.append(c)
    # Если это термины (point is None и есть 'term'), они тоже должны быть в основных
    elif c.get('term') is not None:
        main_chunks.append(c)

print(f"Основных чанков (правила + термины): {len(main_chunks)}")

# ------------------------------------------------------------
# 3. Парсинг Приложения 1 (дорожные знаки)
# ------------------------------------------------------------
def parse_appendix(text, start_marker, end_marker=None, num_pattern=r'^(?P<num>[\d.]+(?:-[\.\d]+)?)\s+[—–-]?\s*'):
    """Универсальный парсер для приложений по номерам в начале строк."""
    start = text.find(start_marker)
    if start == -1:
        return []
    if end_marker:
        end = text.find(end_marker, start)
        if end == -1:
            end = len(text)
    else:
        end = len(text)
    sub = text[start:end]
    pattern = re.compile(num_pattern, re.MULTILINE)
    matches = list(pattern.finditer(sub))
    chunks = []
    for i, m in enumerate(matches):
        start_pos = m.start()
        end_pos = matches[i+1].start() if i+1 < len(matches) else len(sub)
        chunk_text = sub[start_pos:end_pos].strip()
        num = m.group('num')
        if start_marker.strip()=="Приложение 2":
          chunks.append({
              'point': num,
              'text': chunk_text,
              'section': "Дорожная разметка и ее характеристики"
          })
        else:
          chunks.append({
              'point': num,
              'text': chunk_text,
              'section': "Дорожные знаки"
          })

    return chunks

# Парсим знаки (Приложение 1) до начала Приложения 2
sign_chunks = parse_appendix(text, "Приложение 1", "Приложение 2")
print(f"Знаков: {len(sign_chunks)}")

# ------------------------------------------------------------
# 4. Парсинг Приложения 2 (дорожная разметка)
# ------------------------------------------------------------
# Разметка начинается после "1. Горизонтальная разметка" и т.д.
# Но мы можем взять весь раздел до "Основные положения"
marking_chunks = parse_appendix(text, "Приложение 2", "Приложение N 3")
print(f"Разметка: {len(marking_chunks)}")

# ------------------------------------------------------------
# 5. Парсинг Основных положений (включая перечень неисправностей)
# ------------------------------------------------------------
# Для основных положений номера пунктов - целые числа (1., 2., ... 21.)
# Подпункты оставляем внутри текста
base_start = text.find("Приложение N 3")
base_text = text[base_start:]

# Ищем номера вида "1.", "2.", ... в начале строки (без точек внутри)
pattern_base = re.compile(r'^(?P<num>\d{1,2})\.\s+', re.MULTILINE)
matches = list(pattern_base.finditer(base_text))
base_chunks = []
for i, m in enumerate(matches):
    start_pos = m.start()
    end_pos = matches[i+1].start() if i+1 < len(matches) else len(base_text)
    chunk_text = base_text[start_pos:end_pos].strip()
    num = m.group('num')
    base_chunks.append({
        'point': num,
        'text': chunk_text,
        'section': 'Основные положения по допуску транспортных средств к эксплуатации'
    })

print(f"Основных положений: {len(base_chunks)}")

# ------------------------------------------------------------
# 6. Объединяем все списки
# ------------------------------------------------------------
final_chunks = main_chunks + sign_chunks + marking_chunks + base_chunks
print(f"Итоговое количество чанков: {len(final_chunks)}")

# (Опционально) Сохраняем для дальнейшего использования
# import pickle
# with open("/content/final_chunks.pkl", "wb") as f:
#     pickle.dump(final_chunks, f)

for f in final_chunks:
  print(f)

# ------------------------------------------------------------
# 6. Парсинг Перечня неисправностей (отдельная секция) - исправленная версия
# ------------------------------------------------------------
# Находим позицию "Перечень неисправностей" в тексте
pos_perechen = text.find("неисправностей и условий")

# Берем текст от начала перечня до конца документа
perechen_text = text[pos_perechen:]

pattern_perechen = re.compile(r'^(?P<num>\d+\.\d+)\.\s+', re.MULTILINE)

matches = list(pattern_perechen.finditer(perechen_text))

perechen_chunks = []
for i, m in enumerate(matches):
        start_pos = m.start()
        end_pos = matches[i+1].start() if i+1 < len(matches) else len(perechen_text)
        chunk_text = perechen_text[start_pos:end_pos].strip()
        num = m.group('num')
        perechen_chunks.append({
            'point': num,
            'text': chunk_text,
            'section': 'Перечень неисправностей при которых запрещается эксплуатация транспортных средств'
        })

print(f"Перечень неисправностей: {len(perechen_chunks)} пунктов")

    # Выводим первые 5 для проверки
if perechen_chunks:
        print("\nПервые 5 пунктов перечня:")
        for c in perechen_chunks[:5]:
            print(f"  {c['point']}: {c['text'][:100]}...")
else:
      print("Перечень неисправностей не найден в тексте")
      perechen_chunks = []

final_chunks = final_chunks[:-7]

for f in final_chunks:
  print(f)

final_chunks+=perechen_chunks

for f in final_chunks:
  print(f)

"""# Чанки нарезали, теперь генерируем эмбеддинги"""

!pip install faiss-gpu

from sentence_transformers import SentenceTransformer
import faiss
import numpy as np
import pickle
import os

embedding_model = SentenceTransformer('BAAI/bge-m3')

texts_for_embedding = []

for chunk in final_chunks:
    # Определяем тип чанка и формируем текст для эмбеддинга
    if chunk.get('term'):  # Термин
        text = f"Термин: {chunk['term']}. {chunk['text']}"
    elif chunk.get('chapter'):  # Основные правила
        text = f"{chunk['chapter']} - пункт {chunk['point']}: {chunk['text']}"
    elif chunk.get('section'):  # Знаки, разметка, основные положения, перечень
        text = f"{chunk['section']} - пункт {chunk['point']}: {chunk['text']}"
    else:
        text = chunk['text']
    texts_for_embedding.append(text)

print(f"Генерируем эмбеддинги для {len(texts_for_embedding)} чанков...")
chunk_embeddings = embedding_model.encode(
    texts_for_embedding,
    normalize_embeddings=True,
    show_progress_bar=True
)
print("Готово!")

# Создаем FAISS индекс
dimension = chunk_embeddings.shape[1]
index = faiss.IndexFlatIP(dimension)
index.add(chunk_embeddings.astype('float32'))

print(f"Индекс создан, размерность: {dimension}, количество векторов: {index.ntotal}")

faiss.write_index(index, "/content/pdd_index.faiss")
with open("/content/pdd_final_chunks.pkl", "wb") as f:
    pickle.dump(final_chunks, f)

print("Индекс и чанки сохранены в /content/")

"""# Настройка пайплайна"""

def retrieve(query, index, chunks, embedding_model, top_k=3):
    """Находит top_k наиболее релевантных чанков для запроса."""
    query_embedding = embedding_model.encode([query], normalize_embeddings=True)
    distances, indices = index.search(query_embedding.astype('float32'), top_k)

    retrieved = []
    for i, idx in enumerate(indices[0]):
        if idx != -1:
            chunk = chunks[idx]
            retrieved.append({
                'chunk': chunk,
                'score': distances[0][i],
                'text': chunk['text']
            })
    return retrieved

# Тест поиска
test_query = "какие документы должен иметь водитель"
results = retrieve(test_query, index, final_chunks, embedding_model, top_k=3)

print(f"Запрос: {test_query}\n")
for i, res in enumerate(results):
    chunk = res['chunk']
    print(f"Результат {i+1} (оценка: {res['score']:.4f}):")
    if chunk.get('term'):
        print(f"  Термин: {chunk['term']}")
    elif chunk.get('chapter'):
        print(f"  Глава: {chunk['chapter']}, пункт: {chunk['point']}")
    elif chunk.get('section'):
        print(f"  Раздел: {chunk['section']}, пункт: {chunk['point']}")
    print(f"  Текст: {res['text'][:200]}...")
    print("-" * 40)

def generate_answer(query, retrieved_chunks, llm):
    """Генерирует ответ на основе найденных чанков."""
    # Формируем контекст
    context_parts = []
    for i, res in enumerate(retrieved_chunks):
        chunk = res['chunk']

        # Формируем заголовок в зависимости от типа чанка
        if chunk.get('term'):
            header = f"Термин \"{chunk['term']}\""
        elif chunk.get('chapter'):
            header = f"{chunk['chapter']} (пункт {chunk['point']})"
        elif chunk.get('section'):
            header = f"{chunk['section']} (пункт {chunk['point']})"
        else:
            header = "Информация"

        context_parts.append(f"{header}:\n{chunk['text']}")

    context = "\n\n".join(context_parts)

    system_prompt = """
Ты — эксперт по правилам дорожного движения (ПДД) Российской Федерации.
Правила ответа:
1. Используй ТОЛЬКО информацию из предоставленного контекста.
2. Если в контексте нет ответа — скажи "В предоставленном контексте нет информации об этом".
3. Отвечай подробно и развернуто, объясняя все нюансы.
4. Всегда указывай конкретные пункты ПДД (например, "пункт 1.3 ПДД").
5. Если есть исключения — обязательно их перечисли

Важно! Различай:
- Пункты ПДД (нумерация 1.1, 1.2... в основной части)
- Номера дорожной разметки (1.1, 1.2... в Приложении 2)

При ответе о разметке:
- Сплошные линии (1.1, 1.2, 1.3): пересекать запрещено
- Прерывистые линии (1.5, 1.6, 1.7, 1.8): пересекать разрешено
- Комбинированная (1.11): со стороны прерывистой - можно, со стороны сплошной - только при завершении обгона
- Линию 1.2 можно пересекать только для остановки на обочине

Всегда указывай, откуда информация: "Согласно Приложению 2 ПДД..." или "Согласно пункту X ПДД..."
"""

    user_prompt = f"""Контекст для ответа (информация из ПДД):
{context}

Вопрос пользователя: {query}

Ответ:"""

    messages = [
        {"role": "system", "content": system_prompt},
        {"role": "user", "content": user_prompt}
    ]

    response = llm.create_chat_completion(
        messages=messages,
        max_tokens=1024,
        temperature=0.3,
        stop=["<|im_end|>"]
    )

    return response["choices"][0]["message"]["content"]

def rag_pipeline(query, index, chunks, embedding_model, llm, top_k=5):
    """Полный пайплайн RAG: поиск + генерация"""
    retrieved = retrieve(query, index, chunks, embedding_model, top_k)
    answer = generate_answer(query, retrieved, llm)
    return answer, retrieved

"""# Основная программа"""

print("=== RAG-бот по ПДД (Qwen2.5-7B) ===")
print("Введите 'exit' или 'quit' для выхода.\n")
print("Примеры вопросов:")
print("  - Какие документы должен иметь водитель?")
print("  - Можно ли обгонять на пешеходном переходе?")
print("  - Что означает знак 3.20?")
print("  - При какой глубине протектора запрещена эксплуатация?")
print("=" * 50 + "\n")

while True:
    user_query = input("Ваш вопрос: ")
    if user_query.lower() in ['exit', 'quit', 'выход']:
        print("До свидания!")
        break

    if not user_query.strip():
        continue

    print("\n🔍 Ищу в ПДД...")
    answer, sources = rag_pipeline(user_query, index, final_chunks, embedding_model, llm, top_k=5)

    print(f"\n📝 Ответ:\n{answer}\n")

    print("📚 Источники:")
    for i, src in enumerate(sources):
        chunk = src['chunk']

        if chunk.get('term'):
            source_info = f"Термин: {chunk['term']}"
        elif chunk.get('chapter'):
            source_info = f"{chunk['chapter']} (пункт {chunk['point']})"
        elif chunk.get('section'):
            source_info = f"{chunk['section']} (пункт {chunk['point']})"
        else:
            source_info = "Информация"

        print(f"  {i+1}. {source_info} (релевантность: {src['score']:.3f})")
    print("\n" + "="*50 + "\n")